### ISSUE TITLE
Remove unneeded `new` keyword

### ISSUE THREAD

**Issue by joseprio** [lifthrasiir/roadroller#17]
In the output, I noticed that it's using the `new` keyword:
```new Uint16Array(12<<22).fill(1<<15),new Uint8Array(12<<22),0,0,0)```

Correct me if I'm wrong, but I don't think it's necessary and will remove a few bytes!

```Uint16Array(12<<22).fill(1<<15),Uint8Array(12<<22),0,0,0)```

**Comment by joseprio** [comment]
Actually, it seems it's needed; sorry for the noise!

**Comment by lifthrasiir** [comment]
No problem, I actually realized that `12<<22` can be rewritten to `3<<24` while reading this issue so it was not useless!

**Comment by joseprio** [comment]
Not sure how it works internally, but if it's ok to reserve more than needed, what about using `6e7` instead?

**Comment by lifthrasiir** [comment]
That's actually a good idea! `6e7` is a bit too much in my opinion, but `51e6` is definitely okay.
