### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by crisdosaygo** [lifthrasiir/roadroller#21]
Hello, this is incredible.

I checked the license, and "any decoder code is put in the public domain." Is that to be take to mean if I compress a web app bundle with roadroller then the web app code will be public domain? 

I would love to use this to package up resources, but I couldn't if it would change the license of what I applied it to.

**Comment by lifthrasiir** [comment]
No, the decoder code here refers to one generated by Roadroller (also referred as to the "second line" in the README). In the other words I've explicitly waived its copyright so you are absolutely free to use it for any purpose.

**Comment by crisdosaygo** [comment]
Fantastic! Your work on this is so fascinating, seriously. I love the idea of a sort of "binary format" for JavaScript that uses regular ES not WASM. This is such great work!
