### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by CodyJasonBennett** [lifthrasiir/roadroller#4]
Although Node has modules support, many modern build processes still rely on CJS exports.

Maybe support multiple environments with something like rollup:
```js
// rollup.config.js
[
  {
    input: `./index.js`,
    output: { file: `dist/index.js`, format: 'esm' }
  },
  {
    input: `./index.js`,
    output: { file: `dist/index.cjs`, format: 'cjs' }
    ]
  }
]
```

```
// package.json
{
  "main": "dist/index.cjs",
  "module": "dist/index.js"
}
```

**Comment by lifthrasiir** [comment]
I've added support for CommonJS compatibility in 34076090d8c7e651d2392822a0e618298f471824. Could you please check if it works for your use case? Thank you!

**Comment by CodyJasonBennett** [comment]
It does but why is the engine in package.json so high?

**Comment by lifthrasiir** [comment]
Because I haven't tested with other versions of Node.js. (14 in the README is my guess and might not work.) Fixing that is another job to do and I've got so many things to do first... Anyway I'm glad that it works!
